### ISSUE TITLE
ModuleNotFoundError: No module named 'alfworld.env'

### ISSUE THREAD

**Issue by BatmanofZuhandArrgh** [OSU-NLP-Group/LLM-Planner#14]
Traceback (most recent call last):
  File "/home/anhnguyen/Documents/VLM-Planner/src/run_eval.py", line 12, in <module>
    import alfworld.agents.environment
  File "/home/anhnguyen/miniconda3/envs/vlm-planner0/lib/python3.9/site-packages/alfworld/agents/environment/__init__.py", line 2, in <module>
    from alfworld.agents.environment.alfred_thor_env import AlfredThorEnv
  File "/home/anhnguyen/miniconda3/envs/vlm-planner0/lib/python3.9/site-packages/alfworld/agents/environment/alfred_thor_env.py", line 15, in <module>
    from alfworld.env.thor_env import ThorEnv
ModuleNotFoundError: No module named 'alfworld.env'

I'm not sure why alfworld installed in site-packages is not like the official code repo, it's missing the env folder.
I'm on Ubuntu 20.04, it's a conda env python=3.9, alfworld=0.2.2

**Comment by BatmanofZuhandArrgh** [comment]
https://github.com/alfworld/alfworld/tree/master/alfworld/env

I just added this folder to the site-packages

**Comment by chanhee-luke** [comment]
Answered in #17
