### ISSUE TITLE
running run_eval.py gives error

### ISSUE THREAD

**Issue by Acejoy** [OSU-NLP-Group/LLM-Planner#18]
hey all , I am trying to run the evaluation file but it is giving the following errors.
```
(alfworld) srinjoym@user:~/LLM-Planner/src$ python run_eval.py --config gpt4_base_config.yaml 
Traceback (most recent call last):
  File "/data/home/srinjoym/LLM-Planner/src/run_eval.py", line 12, in <module>
    import alfworld.agents.environment
  File "/data/home/srinjoym/miniconda3/envs/alfworld/lib/python3.9/site-packages/alfworld/agents/environment/__init__.py", line 2, in <module>
    from alfworld.agents.environment.alfred_thor_env import AlfredThorEnv
  File "/data/home/srinjoym/miniconda3/envs/alfworld/lib/python3.9/site-packages/alfworld/agents/environment/alfred_thor_env.py", line 15, in <module>
    from alfworld.env.thor_env import ThorEnv
ModuleNotFoundError: No module named 'alfworld.env'

```

I have followed the steps given in readme file.
Any help is appreciated.

**Comment by bowei20222023** [comment]
I have the same error

**Comment by chanhee-luke** [comment]
Hi, there is an error with the underlying simulator (i.e. simulator can't locate the object). So we reverted the code to only generated high-level plans for now. We are working on a fix right now. In the meantime, I recommend a recently released codebase (https://github.com/lbaa2022/LLMTaskPlanning) that covers a similar functionality. Thanks for the interest!

**Comment by chanhee-luke** [comment]
Hi, sorry for the delayed reply. We've revamped the codebase, so please take a look and let me know if there are any further issues. I'll close this issue, but please feel free to re-open it if you need any additional assistance.

Thanks for your interest!

Best,
Luke
